### ISSUE TITLE
how to disable lsp by default

### ISSUE THREAD

**Issue by ccshao** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#1]
A simple question, with  which option could I disable lsp by default? I want to toggle it on when I need it. Thanks!

**Comment by WhoIsSethDaniel** [comment]
Hello,
I have committed a change that allows for the diagnostics to be off when you start neovim. You can use this setting:

require'toggle-lsp-diagnostics'.init({ start_on = false })

You can then toggle the diagnostics on/off as normal.

You will need to have the most recent version of this plugin to see this change.

**Comment by ccshao** [comment]
Thank your very much for the quick help, it works as  expected!
