### ISSUE TITLE
Toggling diagnostics resets my customization

### ISSUE THREAD

**Issue by oredaze** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#11]
When I `<Plug>(toggle-lsp-diag)` they turn off fine, but when I do that again the diagnostics lose any of the settings I have assigned. If I do `<Plug>(toggle-lsp-diag-default)` my customization is back again. This is unexpected behavior. I would like to toggle on/off without it changing any settings. Pressing two keys to turn them back on [properly] is also unacceptable.

**Comment by WhoIsSethDaniel** [comment]
If I understand your problem correctly this behavior is documented in the README:

> You can toggle ALL settings, at once, to either on or off by using the appropriate mapping or command. The toggle-lsp-diag >
> mapping toggles ALL settings either on or off. It does NOT toggle back to a previous state. So, if you toggle off underline, then 
> turn ALL settings off, and then turn ALL settings back on again, the underline will re-appear. To get the settings back to the 
> default you can use the toggle-lsp-diag-default mapping or the :ToggleDiagDefault command.

You shouldn't  need to hit two different keys to go back to your settings. Just use `:ToggleDiagOff` for turning them off and `:ToggleDiagDefault` for toggling them back on. There is no need to use `:ToggleDiagOn` ever in your case. 

The names are odd, but that's for historical reasons.

**Comment by WhoIsSethDaniel** [comment]
btw, sorry for such a long time to answer your bug report. Real-life got in the way.

**Comment by WhoIsSethDaniel** [comment]
I just realized what you were trying to say in your earlier comment. I'll see what I can do about the toggling.

**Comment by WhoIsSethDaniel** [comment]
I believe this issue is fixed.
