### ISSUE TITLE
Any toggle command show error "Invalid buffer name"

### ISSUE THREAD

**Issue by vpeopleonatank** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#3]
When trying any Toggle command, I get the following error 
```
E5108: Error executing lua Vim:E158: Invalid buffer name: 1                                                         │
```

**Comment by WhoIsSethDaniel** [comment]
> When trying any Toggle command, I get the following error
> 
> ```
> E5108: Error executing lua Vim:E158: Invalid buffer name: 1                                                         │
> ```

Hi, I just checked in what I hope will be the solution to your problem. I believe this has to do with recent Neovim changes to the diagnostic API. I made changes that should allow it to work with both the older API and the newer API, but I missed something for the older API (I'm guessing you're running 0.5.0 and not a nightly build, or possibly an older nightly build).  

If that change doesn't work for you: if you're willing to answer some questions and, perhaps, some followup questions this can probably be resolved. I don't see this myself which makes it hard to duplicate.

1) What version of neovim are you running?  You can run `nvim --version` on the command line. Just paste the results into a reply to this.
2) It may help to know where your toggle-lsp-diagnostics is at wrt git. If you can go to the directory where toggle-lsp-disagnostics is installed and run `git rev-parse HEAD` and paste the results here.
3) Did you recently update toggle-lsp-diagnostics? Or was this a recent install? 
4) How are you configuring toggle-lsp-diagnostics? If you can paste your config here.

Thank you.

**Comment by vpeopleonatank** [comment]
I 'm using nvim 0.5.0 stable release. Here is my `nvim --version`
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526
```

After updating to your latest commit, my issue is resolved. Thank you :D

**Comment by WhoIsSethDaniel** [comment]
Good to hear.
