### ISSUE TITLE
Suggested alternative approach

### ISSUE THREAD

**Issue by BlueDrink9** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#7]
I came across this plugin but it didn't quite solve my desires. However, it was a helpful starting point, and I think the results I got might be useful to share here (either to incorporate or for others to copy).

This will automatically grab a user's existing configuration, and toggle between that config and everything off (in contrast to this plugin currently, which ignores the existing config).

```lua
DiagnosticsConfig = vim.diagnostic.config()
DiagnosticsEnabled = true
function ToggleDiagnostics()
   if not DiagnosticsEnabled then
      vim.diagnostic.config(DiagnosticsConfig)
      DiagnosticsEnabled = true
   else
      DiagnosticsConfig = vim.diagnostic.config()
      vim.diagnostic.config({
         virtual_text = false,
         sign = false,
         float = false,
         update_in_insert = false,
         severity_sort = false,
         underline = false,
      })
      DiagnosticsEnabled = false
   end
end
vim.keymap.set("n", "yod", ToggleDiagnostics, { noremap=true, silent=true })
```

**Comment by WhoIsSethDaniel** [comment]
Thanks. I will look into being more tolerant of current configuration.

**Comment by WhoIsSethDaniel** [comment]
fwiw, this plugin's `init()` routine allows passing the same things you pass to `vim.diagnostic.config()`. The idea being that you only call this plugin's `init()`. However I see the value in preserving the current config.

**Comment by WhoIsSethDaniel** [comment]
Thank you for your example code. While `toggle-lsp-diagnostics` will continue to turn everything on by default (as the documentation promises) you *can* pass in the current configuration to `init()` like so:
```lua
require'toggle-lsp-diagnostics'.init(vim.diagnostic.config())
```
This will have the affect you get with your code snippet. Thanks again.

**Comment by BlueDrink9** [comment]
I think the issue is that your toggle doesn't return the behavior to what was specified in the init (as far as I can tell). I think generally people expect a toggle to change between two states, but currently you change between 3 - the current/default config, all on, or all off. It should toggle by default between all off or whatever was set by the init. IMO you should store the init
